import "./globals.css";
import Script from "next/script";

//components
import Navbar from "@/components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="/js/tailwind.js" strategy="beforeInteractive" />
      </head>
      <body className="min-h-screen">
        <div className="w-full bg-gray-100">
          <Navbar/>
          <div className="max-w-screen-xl mx-auto min-h-[calc(100vh-100px)] h-auto px-16 py-4 bg-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
